DELETE FROM "${om_db}"."work__hdmkt_${format}_ps_pro_082_01_concat_history_active";
--
INSERT INTO "${om_db}"."work__hdmkt_${format}_ps_pro_082_01_concat_history_active"
SELECT MST_OFR_ID             ,
       DOC_NBR                ,
       EV_UID                 ,
       LN_NBR                 ,
       KSN_NBR                ,
       STR_GRP_ID             ,
       DVSN_NBR               ,
       DEPT_NBR               ,
       CATG_NBR               ,
       SCAT_NBR               ,
       PRC_STA_DT             ,
       PRC_STA_TM             ,
       PRC_END_DT             ,
       PRC_END_TM             ,
       PRO_GRO_TYP            ,
       PRO_GRO_ID             ,
       X_PRD_TYP_CD           ,
       X_OFFER_TYPE           ,
       X_PCT_CENT_AMT         ,
       X_PRC_MULT_QTY         ,
       ADV_SELL_PRICE         ,
       Y_PRD_TYP_CD           ,
       Y_OFFER_TYPE           ,
       Y_PCT_CENT_AMT         ,
       Y_PRC_MULT_QTY         ,
       MRKDN_IND              ,
       RAIN_CHK_IND           ,
       MTC_TS                 ,
       OFFER_IND              ,
       CHN_ID                 ,
       BUY_GET_IND            ,
       IS_MEMBER_FL           ,
       TELLURIDE_OFR_ID       ,
       IMPT_OFR_ID            ,
       REC_TYPE               ,
       SYWR_OFR_TYP           ,
       SYWR_ITM_THLD_MIN      ,
       SYWR_ITM_THLD_MAX      ,
       SYWR_SPD_THLD_MIN      ,
       SYWR_SPD_THLD_MAX      ,
       SYWR_FOR_EVERY_ITM_CNT ,
       SYWR_FOR_EVERY_DLR_SPD ,
       SYWR_MULTIPIER         ,
       SYWR_POINTS_CAP        ,
       SYWR_POINTS_VALUE      ,
       SYWR_DOLLAR_VALUE      ,
       CONCAT_KEY             ,
       CONCAT_STA_DT          ,
       CONCAT_STA_TM          ,
       CONCAT_END_DT          ,
       CONCAT_END_TM          ,
       ACTIVE_STATUS          ,
       ACTIVITY_ID            ,
       IS_INV_PLANO_FLAG      ,
       IS_SIGN_PREVENTED      ,
       DL_VAL                 ,
       LOSING_ORG_MST_OFR_ID  ,
       LOSING_PRD_GRO_ID      ,
       MOD_ON                 ,
       ID
  FROM "${om_db}"."work__hdmkt_${format}_ps_pro_082_00_concat_history"
 WHERE part_dt = '${lc_part_dt}'
   AND ACTIVE_STATUS != 'DELETE'
   AND DATE(CONCAT_END_DT) >= DATE('${lc_batch_date}');