CREATE EXTERNAL TABLE IF NOT EXISTS `${om_db}`.`work__hdmkt_${format}_ps_pro_082_00_concat_history`
(
MST_OFR_ID             STRING,
DOC_NBR                STRING,
EV_UID                 STRING,
LN_NBR                 STRING,
KSN_NBR                STRING,
STR_GRP_ID             STRING,
DVSN_NBR               STRING,
DEPT_NBR               STRING,
CATG_NBR               STRING,
SCAT_NBR               STRING,
PRC_STA_DT             STRING,
PRC_STA_TM             STRING,
PRC_END_DT             STRING,
PRC_END_TM             STRING,
PRO_GRO_TYP            STRING,
PRO_GRO_ID             STRING,
X_PRD_TYP_CD           STRING,
X_OFFER_TYPE           STRING,
X_PCT_CENT_AMT         STRING,
X_PRC_MULT_QTY         STRING,
ADV_SELL_PRICE         STRING,
Y_PRD_TYP_CD           STRING,
Y_OFFER_TYPE           STRING,
Y_PCT_CENT_AMT         STRING,
Y_PRC_MULT_QTY         STRING,
MRKDN_IND              STRING,
RAIN_CHK_IND           STRING,
MTC_TS                 STRING,
OFFER_IND              STRING,
CHN_ID                 STRING,
BUY_GET_IND            STRING,
IS_MEMBER_FL           STRING,
TELLURIDE_OFR_ID       STRING,
IMPT_OFR_ID            STRING,
REC_TYPE               STRING,
SYWR_OFR_TYP           STRING,
SYWR_ITM_THLD_MIN      STRING,
SYWR_ITM_THLD_MAX      STRING,
SYWR_SPD_THLD_MIN      STRING,
SYWR_SPD_THLD_MAX      STRING,
SYWR_FOR_EVERY_ITM_CNT STRING,
SYWR_FOR_EVERY_DLR_SPD STRING,
SYWR_MULTIPIER         STRING,
SYWR_POINTS_CAP        STRING,
SYWR_POINTS_VALUE      STRING,
SYWR_DOLLAR_VALUE      STRING,
CONCAT_KEY             STRING,
CONCAT_STA_DT          STRING,
CONCAT_STA_TM          STRING,
CONCAT_END_DT          STRING,
CONCAT_END_TM          STRING,
ACTIVE_STATUS          STRING,
ACTIVITY_ID            STRING,
IS_INV_PLANO_FLAG      STRING,
IS_SIGN_PREVENTED      STRING,
DL_VAL                 STRING,
LOSING_ORG_MST_OFR_ID  STRING,
LOSING_PRD_GRO_ID      STRING,
MOD_ON                 STRING,
ID                     STRING
)
PARTITIONED BY (part_dt string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
Location '${PS_Base_Work_Dir_Reference_Feeds}/082_00_concat_history';
MSCK REPAIR TABLE `${om_db}`.`work__hdmkt_${format}_ps_pro_082_00_concat_history`;
